[MeterBand0]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBandSmoothed0]),(#BarWidth#*0.5) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBand1]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBandSmoothed1]),(#BarWidth#*0.5) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBand2]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBandSmoothed2]),(#BarWidth#*0.5) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBand3]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBandSmoothed3]),(#BarWidth#*0.5) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBand4]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBandSmoothed4]),(#BarWidth#*0.5) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBand5]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBandSmoothed5]),(#BarWidth#*0.5) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBand6]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBandSmoothed6]),(#BarWidth#*0.5) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBand7]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBandSmoothed7]),(#BarWidth#*0.5) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBand8]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBandSmoothed8]),(#BarWidth#*0.5) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBand9]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBandSmoothed9]),(#BarWidth#*0.5) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBand10]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBandSmoothed10]),(#BarWidth#*0.5) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBand11]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBandSmoothed11]),(#BarWidth#*0.5) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBand12]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBandSmoothed12]),(#BarWidth#*0.5) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBand13]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBandSmoothed13]),(#BarWidth#*0.5) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBand14]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBandSmoothed14]),(#BarWidth#*0.5) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBand15]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBandSmoothed15]),(#BarWidth#*0.5) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBand16]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBandSmoothed16]),(#BarWidth#*0.5) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBand17]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBandSmoothed17]),(#BarWidth#*0.5) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBand18]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBandSmoothed18]),(#BarWidth#*0.5) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBand19]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBandSmoothed19]),(#BarWidth#*0.5) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBand20]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBandSmoothed20]),(#BarWidth#*0.5) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBand21]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBandSmoothed21]),(#BarWidth#*0.5) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBand22]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBandSmoothed22]),(#BarWidth#*0.5) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBand23]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBandSmoothed23]),(#BarWidth#*0.5) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBand24]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBandSmoothed24]),(#BarWidth#*0.5) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBand25]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBandSmoothed25]),(#BarWidth#*0.5) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBand26]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBandSmoothed26]),(#BarWidth#*0.5) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBand27]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBandSmoothed27]),(#BarWidth#*0.5) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBand28]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBandSmoothed28]),(#BarWidth#*0.5) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBand29]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBandSmoothed29]),(#BarWidth#*0.5) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBand30]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBandSmoothed30]),(#BarWidth#*0.5) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBand31]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBandSmoothed31]),(#BarWidth#*0.5) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBand32]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBandSmoothed32]),(#BarWidth#*0.5) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBand33]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBandSmoothed33]),(#BarWidth#*0.5) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBand34]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBandSmoothed34]),(#BarWidth#*0.5) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBand35]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBandSmoothed35]),(#BarWidth#*0.5) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBand36]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBandSmoothed36]),(#BarWidth#*0.5) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBand37]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBandSmoothed37]),(#BarWidth#*0.5) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBand38]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBandSmoothed38]),(#BarWidth#*0.5) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBand39]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBandSmoothed39]),(#BarWidth#*0.5) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBand40]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBandSmoothed40]),(#BarWidth#*0.5) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBand41]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBandSmoothed41]),(#BarWidth#*0.5) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBand42]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBandSmoothed42]),(#BarWidth#*0.5) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBand43]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBandSmoothed43]),(#BarWidth#*0.5) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBand44]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBandSmoothed44]),(#BarWidth#*0.5) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBand45]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBandSmoothed45]),(#BarWidth#*0.5) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBand46]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBandSmoothed46]),(#BarWidth#*0.5) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBand47]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBandSmoothed47]),(#BarWidth#*0.5) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBand48]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBandSmoothed48]),(#BarWidth#*0.5) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBand49]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBandSmoothed49]),(#BarWidth#*0.5) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1