[MeterBand0]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBand0]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand1]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBand1]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand2]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBand2]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand3]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBand3]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand4]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBand4]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand5]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBand5]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand6]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBand6]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand7]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBand7]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand8]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBand8]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand9]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBand9]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand10]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBand10]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand11]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBand11]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand12]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBand12]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand13]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBand13]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand14]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBand14]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand15]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBand15]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand16]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBand16]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand17]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBand17]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand18]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBand18]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand19]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBand19]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand20]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBand20]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand21]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBand21]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand22]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBand22]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand23]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBand23]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand24]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBand24]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand25]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBand25]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand26]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBand26]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand27]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBand27]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand28]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBand28]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand29]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBand29]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand30]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBand30]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand31]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBand31]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand32]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBand32]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand33]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBand33]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand34]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBand34]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand35]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBand35]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand36]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBand36]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand37]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBand37]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand38]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBand38]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand39]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBand39]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand40]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBand40]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand41]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBand41]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand42]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBand42]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand43]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBand43]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand44]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBand44]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand45]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBand45]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand46]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBand46]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand47]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBand47]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand48]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBand48]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand49]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,(12 + 200),12,(-12 - 200 * [MeasureBand49]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1