[MeterBand0]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand0]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand1]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand1]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand2]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand2]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand3]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand3]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand4]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand4]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand5]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand5]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand6]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand6]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand7]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand7]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand8]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand8]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand9]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand9]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand10]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand10]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand11]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand11]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand12]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand12]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand13]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand13]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand14]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand14]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand15]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand15]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand16]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand16]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand17]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand17]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand18]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand18]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand19]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand19]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand20]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand20]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand21]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand21]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand22]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand22]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand23]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand23]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand24]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand24]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand25]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand25]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand26]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand26]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand27]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand27]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand28]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand28]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand29]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand29]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand30]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand30]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand31]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand31]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand32]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand32]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand33]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand33]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand34]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand34]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand35]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand35]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand36]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand36]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand37]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand37]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand38]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand38]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand39]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand39]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand40]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand40]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand41]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand41]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand42]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand42]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand43]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand43]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand44]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand44]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand45]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand45]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand46]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand46]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand47]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand47]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand48]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand48]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand49]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand49]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand50]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand50]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand51]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand51]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand52]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand52]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand53]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand53]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand54]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand54]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand55]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand55]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand56]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand56]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand57]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand57]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand58]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand58]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand59]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand59]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand60]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand60]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand61]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand61]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand62]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand62]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand63]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand63]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand64]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand64]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand65]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand65]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand66]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand66]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand67]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand67]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand68]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand68]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand69]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand69]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand70]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand70]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand71]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand71]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand72]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand72]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand73]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand73]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand74]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand74]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand75]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand75]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand76]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand76]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand77]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand77]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand78]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand78]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand79]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand79]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand80]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand80]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand81]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand81]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand82]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand82]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand83]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand83]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand84]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand84]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand85]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand85]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand86]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand86]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand87]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand87]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand88]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand88]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand89]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand89]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand90]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand90]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand91]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand91]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand92]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand92]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand93]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand93]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand94]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand94]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand95]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand95]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand96]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand96]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand97]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand97]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand98]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand98]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1
[MeterBand99]
Meter=Shape
X=4R
Y=0r
Shape=Rectangle 0,0,12,(12+200*[MeasureBand99]),(12*0.5) | Fill Color 160,224,64,255 | StrokeWidth 0
DynamicVariables=1